### ISSUE TITLE
Add copy to clipboard function

### ISSUE THREAD

**Issue by cwang66** [rr-/shot#1]
Add copy to clipboard function

**Comment by rr-** [comment]
The question is, what should be copied: the path to the output file, or the canvas itself?

**Comment by cwang66** [comment]
canvas, like SnippingTool on windows,  default copy image to clipboard, convenient to paste to ppt

**Comment by cwang66** [comment]
And , shot -h or shot --help can't work on windows, Can you fix it.

**Comment by rr-** [comment]
> And , shot -h or shot --help can't work on windows, Can you fix it.

With Windows `cmd.exe`, either you're able to create windows at expense of being able to log things to console, or you can log to console but can't create windows (at least not without `cmd.exe` popping up). Never both. It's how Windows works: http://stackoverflow.com/a/3370017/2016221

`shot` needs to be able to create windows because of `-i` that spawns selection window.

One solution is to move `-i` to a separate executable, `shot-interactive.exe` and spawn it as a new graphic process from within `shot.exe`. In my opinion, this is stupid.

IMO the best option here is to link `docs/help.txt` from within `README.txt` to make it more visible.

**Comment by rr-** [comment]
There's another option I haven't considered: I can show a graphical message box to show the help. This feels weird, especially if you're running the program from within `cmd.exe`. Then again, I guess seeing help in a weird way is better than not seeing it at all, and implementing this requires much less effort when compared to pulling out a great deal of code to a separate executable...

EDIT: on the other hand, there's cygwin, which handles the output just fine. Message boxes would be very negative there.

**Comment by rr-** [comment]
@cwang66 I've implemented `-c` / `--clipboard`, let me know if it works for you.

Temporary build: http://tmp.sakuya.pl/f/shot.exe

**Comment by cwang66** [comment]
I got it, thank you very much!!  it can't work for me, "shot -i -c" or "shot -c" can't copy image to clipboard

**Comment by rr-** [comment]
I've tested on a virtual machine with Windows 7 and it works there. I'll check it again on Thursday with a non-virtual Windows installation, when I get access to it.

**Comment by cwang66** [comment]
what command do you enter in cmd

**Comment by rr-** [comment]
`shot -c`, then I open up MS Paint and paste it there.

**Comment by cwang66** [comment]
shot -c，can be copied to the paint MS，can not be copied to the ms powerpoint

**Comment by rr-** [comment]
@cwang66 sorry for the delay; it should be fixed in newest HEAD.

https://tmp.sakuya.pl/f/shot.exe
